# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        types_or: [c, c++, cuda, fortran]
    -   id: end-of-file-fixer
        types_or: [c, c++, cuda, fortran]
    -   id: check-yaml
    -   id: check-added-large-files
        types_or: [c, c++, cuda, fortran]
-   repo: https://github.com/pocc/pre-commit-hooks.git
    rev: v1.3.5
    hooks:
    -   id: cpplint
        args: [--linelength=120]
        types_or: [c, c++, cuda]
