name: Docs

on:
  pull_request:
  push:
    branches: [master]
permissions:
  contents: write

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Python setup
      uses: actions/setup-python@v3

    - name: doxygen
      run: sudo apt-get install doxygen -y

    - name: Requirements
      run: |
       pip3 install sphinx
       pip3 install sphinx_rtd_theme
       pip3 install breathe
       pip3 install sphinx_sitemap

    - name: Build docs
      run: cd doc && python3 -m sphinx.cmd.build -M html source _build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: doc/_build/html # The folder the action should deploy.
