name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Python setup
      uses: actions/setup-python@v3

    - name: Cpplint installation
      run: pip install cpplint

    - name: Pre-commit run
      uses: pre-commit/action@v3.0.0
